/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yuqianhao_support_io_NativeDataIO_V0 */

#ifndef _Included_com_yuqianhao_support_io_NativeDataIO_V0
#define _Included_com_yuqianhao_support_io_NativeDataIO_V0
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yuqianhao_support_io_NativeDataIO_V0
 * Method:    writeV0
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_yuqianhao_support_io_NativeDataIO_1V0_writeV0
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_yuqianhao_support_io_NativeDataIO_V0
 * Method:    readV0
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yuqianhao_support_io_NativeDataIO_1V0_readV0
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
